name: bluebikes_hourly_features_pipeline

on:
  schedule:
    - cron: '2 * * * *' # Runs every hour at 2 minutes past
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-hourly-feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt # Install dependencies

      - name: Run hourly feature pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME}}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY}}
        run: python -m pipelines.bluebikes_feature_pipeline_hourly
