name: bluebikes_model_training_pipeline

on:
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 2 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install dependencies

      - name: Train model on new data
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME}}
        run: python -m pipelines.bluebikes_model_training_pipeline
